### ISSUE TITLE
2.4.3 Fabric Version of mod crashes when trying to create world

### ISSUE THREAD

**Issue by NolanHewitt** [ApolloDatapacks/tectonic#285]
Crashes on clicking create world. Previous version works without issue.

[crash-2025-02-17_03.20.04-client.txt](https://github.com/user-attachments/files/18822898/crash-2025-02-17_03.20.04-client.txt)

Tested using only Tectonic, Lithostitched, and Quilted Fabric API

I also tested it with Fabric and the Fabric API to make sure it wasn't a quilt issue and it still crashed.

[crash-2025-02-17_03.23.11-client.txt](https://github.com/user-attachments/files/18822965/crash-2025-02-17_03.23.11-client.txt)

**Comment by Apollounknowndev** [comment]
Fixed in 2.4.4.

**Comment by Alasofia** [comment]
Any chance of a 1.21.4 version of 2.4.4? Still broken there.

**Comment by Apollounknowndev** [comment]
If there's an issue on 1.21.4 then it's for a separate reason, please create a new report for that
